sim = true
outdir = "results/vagrant/federated-svd/cent/"
project_id = 17306


[[clients]]
coordinator = true
fc_username = 'user'
data = [
    "data/federated-svd/cent/input.csv",
    "configs/vagrant/federated-svd/config.yaml"
]






